version: 2
jobs:
  build:
    docker:
      - image: binded/node-ci:base
    working_directory: /ci/project
    environment:
      - BASH_ENV: .circleci/bash_env.sh
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys:
            - node-modules
      - run: build
      - save_cache:
          key: node-modules
          paths:
            - node_modules
      - run: run-test
      - run: release
      - deploy:
          command: deploy
