version: 2
jobs:
  build:
    docker:
      # custom image -- includes helm, kubectl, terraform, etc.
      - image: binded/ci:1.0.0
    working_directory: /ci
    steps:
      - setup_remote_docker
      - checkout:
          path: /ci/repo
      - run: make build
      - run: make test
      - run: make push
      - deploy:
          command: |
            make deploy
